fail_fast: false
exclude: ^(\.cache|\.venv|\.vs|\.zed|docs|out|rom)/

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
      - id: check-yaml
        files: \.(yaml|yml|clang-format|clang-tidy|clangd)$
      - id: check-json
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-illegal-windows-names
      - id: check-merge-conflict
      - id: mixed-line-ending

  - repo: local
    hooks:
      - id: clang-format
        name: clang-format
        entry: clang-format
        args: ["-style=file", "-i"]
        language: system
        types_or: [c++]
        files: ^(src|tests)/

  - repo: local
    hooks:
      - id: clang-tidy
        name: clang-tidy
        entry: clang-tidy
        args: ["-p=."]
        language: system
        types_or: [c++]
        files: ^(src|tests)/
