name: dev-ci
run-name: ${{ github.actor }} is building Mayones
on: [push]

jobs:

  build:
    name: Build
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      # - name: Setup LLVM
      #   run: choco install llvm --version 21.1.3

      # - name: Setup Python
      #   uses: actions/setup-python@v3

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11

      - name: Setup CMake
        uses: lukka/get-cmake@latest
        with:
          cmakeVersion: "^4.2.3"
          ninjaVersion: "^1.13.2"

      - name: Configure build
        uses: lukka/run-cmake@v10
        with:
          configurePreset: 'msvc-debug'
          configurePresetAdditionalArgs: "['-DBUILD_TESTING=ON']"

      - name: Pre-commit
        uses: pre-commit/action@v3.0.1
        with:
          extra_args: --all-files

      - name: Build
        uses: lukka/run-cmake@v10
        with:
          buildPreset: 'msvc-debug'

      - name: Test
        uses: lukka/run-cmake@v10
        with:
          testPreset: 'msvc-debug'
